baseURL = "https://blog.liubang.cc"
title = "星河拾贝录"
theme = "DoIt"
copyright = "Copyright © 2019-2026 LiuBang. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

# Pagination
[pagination]
pagerSize = 30
path = "page"

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true
timeout = "120s"

[outputs]
home = ["HTML", "RSS", "JSON"]

# 分类
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[build]
writeStats = true

[security.funcs]
getenv = ['^HUGO_', '^CI$', 'PWD']
