[goldmark]
[goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[goldmark.extensions.passthrough]
enable = true
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
[goldmark.parser.attribute]
block = false
title = true

[goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
# DoIt requires noClasses = false to use its own highlight styles
noClasses = false
style = "onedark"
tabWidth = 2
