[[main]]
  identifier = "posts"
  pre = ""
  post = ""
  name = "文章"
  url = "/posts/"
  title = ""
  weight = 1

[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = ""
  weight = 2

[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = ""
  weight = 3

[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "专栏"
  url = "/series/"
  title = ""
  weight = 4

[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "关于"
  url = "/about/"
  title = ""
  weight = 5
